chore: add release workflow
digidem/mapeo-settings-builder pull request #55
Opened 2024-04-10 16:59 UTC by tomasciccola

this should close #54

2024-05-29 15:31 UTC, tomasciccola commented
missing for this is adding the npm token to the project

2024-06-05 15:29 UTC, EvanHahn requested changes
LGTM other than my two nitpicks.

2024-06-05 15:29 UTC, EvanHahn commented on .github/workflows/release.yml
> +          npm-tag: ${{ startsWith(github.event.inputs.semver, 'pre') && 'alpha' || 'latest' }}
This comment doesn't match the behavior. I think we should use the `next` dist-tag.

```suggestion
          npm-tag: ${{ startsWith(github.event.inputs.semver, 'pre') && 'next' || 'latest' }}
```

2024-06-05 15:29 UTC, EvanHahn commented on .github/workflows/release.yml
> +            npm install
This should use `npm ci`. I opened [a PR to do the same on `mapeo-core-next` too](https://github.com/digidem/mapeo-core-next/pull/694).

```suggestion
            npm ci
```

2024-06-05 18:40 UTC, EvanHahn approved these changes

2024-06-06 14:26 UTC, merged